name: sandwich-maker
services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - backend
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  server-a:
    build:
      context: ./backend/server-a
    ports:
      - "12345:8080"
    networks:
      - backend
    environment:
      - mssqlHost=mssql
      # This should use Docker secrets in production
      - mssqlPassword=${MSSQL_SA_PASSWORD}
      - RabbitMQ_Host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy


  server-b:
    build:
      context: ./backend/server-b
    environment:
      - RabbitMQ_Host=rabbitmq
    networks:
      - backend
    depends_on:
      mssql:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - sqlvolume:/var/opt/mssql

  frontend:
    build:
      context: ./frontend
    ports:
      - "12346:80"
    networks:
      - backend
    depends_on:
      - server-a

volumes:
  sqlvolume:

networks:
  backend:
