/*
 * Make me a sandwich
 *
 * This is the Swagger 2.0 API for Web Architectures course group project work. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: mikko.nurminen@tuni.fi
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using server_a.ApiModels;
using server_a.Helpers;

namespace server_a.Api
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class SandwichApi(SandwichCollection sandwichCollection) : ControllerBase
    {
        private readonly SandwichCollection _sandwichCollection = sandwichCollection;

        /// <summary>
        /// Add a new sandwich to the store. Needs an API key.
        /// </summary>
        /// <param name="sandwich">Sandwich object that needs to be added to the store</param>
        /// <response code="400">Invalid input</response>
        [HttpPost]
        [Route("/v1/sandwich")]
        //Require Auth
        public virtual IActionResult AddSandwich([FromBody] Sandwich sandwich)
        {
            sandwich.Id = _sandwichCollection.Count;
            _sandwichCollection.Add(sandwich);

            return Ok(sandwich);
        }

        /// <summary>
        /// Deletes a sandwich
        /// </summary>

        /// <param name="sandwichId">Sandwich id to delete</param>
        /// <response code="400">Invalid input</response>
        /// <response code="404">Sandwich not found</response>
        [HttpDelete]
        [Route("/v1/sandwich/{sandwichId}")]
        //require auth
        public IActionResult DeleteSandwich([FromRoute][Required] long? sandwichId)
        {
            var sandwich = _sandwichCollection.FirstOrDefault(s => s.Id == sandwichId);
            if (sandwich == null)
            {
                return NotFound();
            }

            _sandwichCollection.Remove(sandwich);
            return Ok();
        }

        /// <summary>
        /// Find sandwich by ID
        /// </summary>
        /// <remarks>Returns a single sandwich</remarks>
        /// <param name="sandwichId">ID of sandwich to return</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Invalid input</response>
        /// <response code="404">Sandwich not found</response>
        [HttpGet]
        [Route("/v1/sandwich/{sandwichId}")]
        //Require Auth
        [ProducesResponseType(statusCode: 200, type: typeof(Sandwich))]
        public IActionResult GetSandwichById([FromRoute][Required] long? sandwichId)
        {
            var sandwich = _sandwichCollection.FirstOrDefault(s => s.Id == sandwichId);
            if (sandwich == null)
            {
                return NotFound();
            }

            return Ok(sandwich);
        }

        /// <summary>
        /// Get a list of all sandwiches. Empty array if no sandwiches are found.
        /// </summary>
        /// <response code="200">successful operation</response>
        [HttpGet]
        [Route("/v1/sandwich")]
        [ProducesResponseType(statusCode: 200, type: typeof(List<Sandwich>))]
        public IActionResult GetSandwiches()
        {
            return Ok(_sandwichCollection);
        }

        /// <summary>
        /// Updates a sandwich in the store with JSON in body
        /// </summary>

        /// <param name="sandwichId">ID of sandwich to return</param>
        /// <param name="newSandwich">Sandwich object that needs to be added to the store</param>
        /// <response code="400">Invalid input</response>
        /// <response code="404">Sandwich not found</response>
        [HttpPut]
        [Route("/v1/sandwich/{sandwichId}")]
        //Require Auth
        public virtual IActionResult UpdateSandwich([FromRoute][Required] long? sandwichId,
         [FromBody] Sandwich newSandwich)
        {
            var sandwich = _sandwichCollection.FirstOrDefault(s => s.Id == sandwichId);
            if (sandwich == null)
            {
                return NotFound();
            }
            var id = sandwich.Id;
            newSandwich.Id = id;
            _sandwichCollection.Remove(sandwich);
            _sandwichCollection.Add(newSandwich);

            return Ok(newSandwich);
        }
    }
}
